cc_library (
	name = "leetcode",
	hdrs = [

	],
	srcs = [

	],
)

cc_test (
	name = "all_tests",
	srcs = [

	],
	deps = [
		":leetcode",
		"@googletest//:gtest_main",
	]
)

cc_test (
	name = "current_test",
	srcs = [

	],
	deps = [
		":leetcode",
		"@googletest//:gtest_main",
	]
)

